python bench.py PMLB_base.yaml 1089_USCrime
python bench.py PMLB_base.yaml 1027_ESL
python bench.py PMLB_base.yaml 1028_SWD
python bench.py PMLB_base.yaml 1029_LEV
python bench.py PMLB_base.yaml 1030_ERA
python bench.py PMLB_base.yaml 1096_FacultySalaries
python bench.py PMLB_base.yaml 192_vineyard
python bench.py PMLB_base.yaml 197_cpu_act
python bench.py PMLB_base.yaml 210_cloud
python bench.py PMLB_base.yaml 225_puma8NH
python bench.py PMLB_base.yaml 227_cpu_small
python bench.py PMLB_base.yaml 228_elusage
python bench.py PMLB_base.yaml 230_machine_cpu
python bench.py PMLB_base.yaml 523_analcatdata_neavote
python bench.py PMLB_base.yaml 547_no2
python bench.py PMLB_base.yaml 663_rabe_266
python bench.py PMLB_base.yaml 666_rmftsa_ladata
python bench.py PMLB_base.yaml 678_visualizing_environmental
python bench.py PMLB_base.yaml 687_sleuth_ex1605
python bench.py PMLB_base.yaml 695_chatfield_4
python bench.py PMLB_base.yaml 706_sleuth_case1202
python bench.py PMLB_base.yaml 712_chscase_geyser1
python bench.py PMLB_base.yaml 229_pwLinear
python bench.py PMLB_base.yaml 485_analcatdata_vehicle
python bench.py PMLB_base.yaml 522_pm10
python bench.py PMLB_base.yaml 527_analcatdata_election2000
python bench.py PMLB_base.yaml 542_pollution
python bench.py PMLB_base.yaml 556_analcatdata_apnea2
python bench.py PMLB_base.yaml 557_analcatdata_apnea1
python bench.py PMLB_base.yaml 560_bodyfat
python bench.py PMLB_base.yaml 561_cpu
python bench.py PMLB_base.yaml 659_sleuth_ex1714
python bench.py PMLB_base.yaml 665_sleuth_case2002
python bench.py PMLB_base.yaml 690_visualizing_galaxy
python bench.py PMLB_base.yaml 519_vinnie
python bench.py PMLB_base.yaml 529_pollen
python bench.py PMLB_base.yaml 503_wind
python bench.py PMLB_base.yaml 505_tecator